#! /usr/bin/env python3
# -*- coding: Utf-8 -*
##
## EPITECH PROJECT, 2019
## 109titration_2019
## File description:
## 109titration
##

import os, sys

from titration_error_handling.is_str_float import is_str_float
from titration_error_handling.is_str_int import is_str_int
from titration_error_handling.check_pH_values import check_pH_values as is_str_pH
from titration_error_handling.error_handler import error_handler
from titration_error_handling.usage import usage

from compute_titration import compute_titration

def main(ac: int, av: list):

    if ac != 2:
        error_handler()

    if av[1] == "-h":
        usage()
        return 0

    if not os.path.exists(av[1]) or (os.path.splitext(av[1]))[-1] != ".csv":
        error_handler()

    stock = []

    with open(av[1], "r") as fd:
        stock = [line.split(';') for line in fd.read().splitlines()]

    if len(stock) <= 2:
        error_handler()

    for element in stock:
        if len(element) != 2 or (is_str_float(element[0]) is False) or (is_str_pH(element[1]) is False):
            error_handler()

    compute_titration(stock)
    return 0

if __name__ == "__main__":
    sys.exit(main(len(sys.argv), sys.argv))