#! /usr/bin/env python3
# -*- coding: Utf-8 -*
##
## EPITECH PROJECT, 2019
## 109titration_2019
## File description:
## 109titration
##

import sys

import os

from error_handling.usage import usage
from error_handling.error_handler import error_handler

from error_handling.check_pH_values import check_pH_values
from error_handling.is_str_float import is_str_float
from error_handling.is_str_int import is_str_int

def main(ac: int, av: list):

    if ac != 2 :
        error_handler()

    if av[1] == "-h":
        usage()
        return 0

    if not os.path.exists(av[1]) or (os.path.splitext(av[1]))[-1] != ".csv" :
        error_handler()

    stock = list()

    with open(av[1], "r") as fd :
        stock = [line.split(';') for line in fd.read().splitlines()]

    if len(stock) <= 0 :
        error_handler()

    for element in stock :
        if len(element) != 2 or not is_str_float(element[0]) or not check_pH_values(element[1]) :
            error_handler()

    print(stock)
    return 0

if __name__ == "__main__":
    sys.exit(main(len(sys.argv), sys.argv))