#! /usr/bin/env python3
# -*- coding: Utf-8 -*
##
## EPITECH PROJECT, 2019
## 109titration_2019
## File description:
## 109titration
##

import sys

import os

from error_handling.usage import usage
from error_handling.error_handler import error_handler

from error_handling.check_pH_values import check_pH_values
from error_handling.is_str_float import is_str_float
from error_handling.is_str_int import is_str_int

from titration import titration
from transform_to_float_array import transform_to_float_array

from print_first_derivative import print_first_derivative
from print_second_derivative import print_second_derivative
from print_equivalence_point import print_equivalence_point
from reattribute_stock import reattribute_stock

def main(ac: int, av: list):

    if ac != 2 :
        error_handler()

    if av[1] == "-h":
        usage()
        return 0

    if not os.path.exists(av[1]) or (os.path.splitext(av[1]))[-1] != ".csv" :
        error_handler()

    stock = list()

    with open(av[1], "r") as fd :
        stock = [line.split(';') for line in fd.read().splitlines()]

    if len(stock) <= 2 :
        error_handler()

    for element in stock :
        if len(element) != 2 or not is_str_float(element[0]) or not check_pH_values(element[1]) :
            error_handler()

    stock = transform_to_float_array(stock)
    first_derivative = titration(stock)
    print_first_derivative(first_derivative, stock)
    print()
    pos_eq = print_equivalence_point(first_derivative, stock)
    print()
    stock = reattribute_stock(stock, first_derivative)
    second_derivative = titration(stock)
    print_second_derivative(second_derivative, stock)
    print()

    return 0

if __name__ == "__main__":
    sys.exit(main(len(sys.argv), sys.argv))